AWSTemplateFormatVersion: 2010-09-09

Resources:
  CoursesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Courses"
      AttributeDefinitions:
        - AttributeName: "courseID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "courseID"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"

  # NotesTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: "Notes"
  #     AttributeDefinitions:
  #       - AttributeName: "courseID"
  #         AttributeType: "S"
  #       - AttributeName: "lectureNo"
  #         AttributeType: "S"
  #       # - AttributeName: "File"
  #       #   AttributeType: "S"
  #     KeySchema:
  #       - AttributeName: "courseID"
  #         KeyType: "HASH"
  #       - AttributeName: "lectureNo"
  #         KeyType: "RANGE"
  #     BillingMode: "PAY_PER_REQUEST"

  NotesS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: b00932103-notes-system
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      # AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - PUT
              - POST
              - DELETE
              - GET
            AllowedOrigins:
              - "*"

  NotesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref NotesS3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${NotesS3Bucket}/*"

          - Effect: Allow
            Principal: "*"
            Action: s3:PutObject
            Resource: !Sub "arn:aws:s3:::${NotesS3Bucket}/*"