AWSTemplateFormatVersion: 2010-09-09

Resources:
  CoursesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Courses"
      AttributeDefinitions:
        - AttributeName: "courseID"
          AttributeType: "S"
        # - AttributeName: "Name"
        #   AttributeType: "S"
        # - AttributeName: "Instructor"
        #   AttributeType: "S"
        # - AttributeName: "Password"
        #   AttributeType: "S"
        # - AttributeName: "Students"
        #   AttributeType: "SS"
      KeySchema:
        - AttributeName: "courseID"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"

  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Notes"
      AttributeDefinitions:
        - AttributeName: "courseID"
          AttributeType: "S"
        - AttributeName: "lectureNo"
          AttributeType: "S"
        # - AttributeName: "File"
        #   AttributeType: "S"
      KeySchema:
        - AttributeName: "courseID"
          KeyType: "HASH"
        - AttributeName: "lectureNo"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"