AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  NotesTextExtract:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: NotesTextExtract
      Runtime: python3.8
      Handler: notesTextract.lambda_handler
      Role: arn:aws:iam::967969319497:role/LabRole
      CodeUri: s3://b00932103backend/LambdaFunctions/notesTextract.zip
      # Code:
      #   Bucket: b00932103backend
      #   Key: LambdaFunctions/notesTextract.zip
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref NotesS3Bucket
            Events:
              - s3:ObjectCreated:Put
              - s3:ObjectCreated:Post
              - s3:ObjectCreated:Copy
              - s3:ObjectCreated:CompleteMultipartUpload
      # Events:
      #   S3Event:
      #     Type: S3
      #     Properties:
      #       Bucket: !Ref NotesS3Bucket
      #       Events: s3:ObjectCreated:*
      #   S3EventPut:
      #     Type: S3
      #     Properties:
      #       Bucket: !Ref NotesS3Bucket
      #       Events: s3:ObjectCreated:Put
      #   S3EventPost:
      #     Type: S3
      #     Properties:
      #       Bucket: !Ref NotesS3Bucket
      #       Events: s3:ObjectCreated:Post
      #   S3EventCopy:
      #     Type: S3
      #     Properties:
      #       Bucket: !Ref NotesS3Bucket
      #       Events: s3:ObjectCreated:Copy
      #   S3EventMultipartUpload:
      #     Type: S3
      #     Properties:
      #       Bucket: !Ref NotesS3Bucket
      #       Events: s3:ObjectCreated:CompleteMultipartUpload

  NotesS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: b00932103-notes-system
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      # AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - PUT
              - POST
              - DELETE
              - GET
            AllowedOrigins:
              - "*"

  NotesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref NotesS3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${NotesS3Bucket}/*"
          - Effect: Allow
            Principal: "*"
            Action: s3:PutObject
            Resource: !Sub "arn:aws:s3:::${NotesS3Bucket}/*"

Outputs:
  NotesBucketName:
    Value: !Ref NotesS3Bucket
    Description: The name of the S3 bucket for notes
